### ISSUE TITLE
Document that the payload must be UTF8 encoded

### ISSUE THREAD

**Issue by edmorley** [hapijs/hawk#152]
We're using [hawkrest](https://github.com/kumar303/hawkrest) server-side and are migrating users of our API to it from our legacy oauth credentials. As part of the transition one of our submitters was getting intermittent failures submitting to our API, which were showing in our API logs as:

[2015-11-02 12:57:02,796] WARNING [hawkrest:81] access denied: MacMismatch: MACs do not match; ours: REDACTED theirs: REDACTED 
(which comes from mohawk: https://github.com/kumar303/mohawk/blob/0.3.0/mohawk/base.py#L50)

It turned out that these were due to them not UTF8 encoding the payload passed to `hawk.client.header()`.

This isn't mentioned anywhere in the README, only in passing here:
 https://github.com/hueniverse/hawk/blob/v3.1.0/lib/client.js#L36

Would it be possible to make this clearer in the readme? Perhaps it's worth having a troubleshooting section?

Thanks :-)

**Comment by hueniverse** [comment]
I'll take a PR.

**Comment by edmorley** [comment]
> I'll take a PR.

Sure, happy to open one - there just seems to be a difference between documented spec, Hawk source and downstream mohawk implementation - and I'm not sure which is correct.

ie the Hawk docs [say](https://github.com/hueniverse/hawk/blame/fae8544f0d0a0ad3abc766ebafe24a3058c75e19/README.md#L264-L270):
```markdown
### Payload Validation
**Hawk** provides optional payload validation. When generating the authentication header, the client calculates a payload hash
using the specified hash algorithm. The hash is calculated over the concatenated value of (each followed by a newline character):
* ...
* ...
* the request payload prior to any content encoding (the exact representation requirements should be specified by the server for payloads other than simple single-part ascii to ensure interoperability)
```

Whereas the Hawk source [comments](https://github.com/hueniverse/hawk/blob/v3.1.0/lib/client.js#L36):
```js
        payload: '{"some":"payload"}',                      // UTF-8 encoded string for body hash generation (ignored if hash provided)
```

And mohawk [assumes](https://github.com/kumar303/mohawk/blob/3c6f342338afb91eaa0d75efb1a6148c4c0795d2/mohawk/util.py#L56-L58) the client has UTF8 encoded:
```python
        # Make sure we are about to hash binary strings.
        if not isinstance(p, six.binary_type):
            p = p.encode('utf8')
```

Should I:
1. Fix the README comments to say that UTF8 encoding must be performed when not dealing with straight ascii
2. Mention it depends on the server, but state that if using mohawk, UTF8 is expected
3. Something else?

Many thanks :-)

**Comment by hueniverse** [comment]
The payload needs to be hashed based on it raw HTTP representation which is 7bit ascii and before any HTTP content encoding is applied (gzip, etc.).
