### ISSUE TITLE
Complete example of server implementation

### ISSUE THREAD

**Issue by harryi3t** [hapijs/hawk#215]
People may directly use the example given in the README to implement a hawk server.
This already covers the basics but not all the cases.

For eg. using the [boom](https://www.npmjs.com/package/boom) error object to construct the header:
 1. When no 'Authorization' header is sent from client, server should return `www-authenticate: hawk` header
 2. When the credentials are right but the timestamp is in-correct then send the current timestamp in the header

I have opened this issue just to request to update the README's server example to include these missing cases.

**Comment by JSteunou** [comment]
@harryi3t for curiosity, how the current timestamp should be send back? Special header name?

**Comment by harryi3t** [comment]
@JSteunou It can be included in the `www-authenticate` header, just like in other auths.
For eg, if your credentials are incorrect in digest auth you will get
```
WWW-Authenticate: Digest realm="Users", nonce="xxxxxxx", qop="auth"
```

So for hawk auth too there should be some standard way, like
```
WWW-Authenticate: hawk timestamp="xxxxxxx"
```

**Comment by harryi3t** [comment]
@hueniverse Hey, what was the resolution for this? I can't find any documentation update for this.

**Comment by hueniverse** [comment]
There isn't any. I am not actively working on this anymore. I will keep it maintained for existing users but I am not working to get wider adoption.
