### ISSUE TITLE
Remove browser exports

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hawk#253]
The code is outdated and should not be used anyway. You should do your own webpack processing of this module.

**Comment by djmitche** [comment]
Note that webpack processing is complicated, since @hapi/sntp uses node-specific APIs.

**Comment by hueniverse** [comment]
Happy to move sntp to Mozilla as well.

**Comment by djmitche** [comment]
I don't think that would help -- there's no way to do UDP from a browser.
