### ISSUE TITLE
Could not find a declaration file for module '@hapi/hawk'. 

### ISSUE THREAD

**Issue by klikpaspor** [hapijs/hawk#256]
Could not find a declaration file for module '@hapi/hawk'. 'c:/aa/v/node_modules/@hapi/hawk/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/hapi__hawk` if it exists or add a new declaration (.d.ts) file containing `declare module '@hapi/hawk';`ts(7016)

**Comment by klikpaspor** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fhapi__hawk - Not found
npm ERR! 404
npm ERR! 404  '@types/hapi__hawk@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by hueniverse** [comment]
I am unlikely to add TS support anytime soon. You might want to see if you can copy the definition for hawk over to @hapi/hawk.
