### ISSUE TITLE
Add TypeScript typings

### ISSUE THREAD

**Issue by amaurymartiny** [hapijs/hawk#269]
#### Support plan

* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*: 13.6.0
* *module version*: 4.0.0
* *environment* (e.g. node, browser, native): All
* *used with* (e.g. hapi application, another framework, standalone, ...): another framework
* *any other relevant information*:

#### What problem are you trying to solve?

Right now, I need to create a `.d.ts` file and add

```ts
declare module '@hapi/hawk';
```

and exports from this module have no typings.

#### Do you have a new or modified API suggestion to solve the problem?

No.

**Comment by hueniverse** [comment]
This will happen over time as TS support is added to the entire org. The effort is going to take a while unless we are able to get funding via https://www.gofundme.com/manage/hapi-ts
